name: 'Deploy'

on:
  workflow_call:
    secrets:
      aws-access-key:
        required: true
      aws-secret-key:
        required: true
    inputs:
      region:
        required: true
        type: string
      cluster:
        required: true
        type: string
      config-name:
        required: true
        type: string
      profile-name:
        required: true
        type: string
      launch-type:
        required: true
        type: string
      project-name:
        required: true
        type: string
      target-group-arn:
        required: true
        type: string
      container-name:
        required: true
        type: string
      container-port:
        required: true
        type: string
      image-repo:
        required: true
        type: string
      docker-folder:
        required: true
        type: string

jobs:
 buildAndDeployImage:
  name: 'Build docker image and deploy'
  runs-on: ubuntu-latest
  steps:
  - name: 'Setup ECS-CLI'
    uses: marocchino/setup-ecs-cli@v1
    with:
      version: v1.18.1

  - name: 'Checkout project'
    uses: actions/checkout@v2

  - name: 'Login to Amazon ECR, build & upload docker image'
    if: ${{ github.event.inputs.command == 'deploy' }}
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-key }}
      AWS_REGION: ${{ inputs.region }}
    run: |
      ./gradlew jib --image ${{ inputs.image-repo }} -PgithubRun

  - name: 'Cluster configuration'
    working-directory: docker/${{ inputs.docker-folder }}
    run: |
      ecs-cli configure --cluster ${{ inputs.cluster }} --default-launch-type ${{ inputs.launch-type }} --config-name ${{ inputs.config-name }} --region ${{ inputs.region }}
      ecs-cli configure profile --access-key ${{ secrets.aws-access-key }} --secret-key ${{ secrets.aws-secret-key }} --profile-name ${{ inputs.profile-name }}

  - name: 'Compose service up - deploying the new service'
    if: ${{ github.event.inputs.command == 'deploy' }}
    working-directory: docker/${{ inputs.docker-folder }}
    run: |
      ecs-cli compose --project-name ${{ inputs.project-name }} service up --create-log-groups --cluster-config ${{ inputs.config-name }} --ecs-profile ${{ inputs.profile-name }} --target-group-arn ${{ inputs.target-group-arn }} --container-name ${{ inputs.container-name }} --container-port ${{ inputs.container-port }}

  - name: 'Compose service ${{ github.event.inputs.command }}'
    if: ${{ github.event.inputs.command != 'deploy' && github.event.inputs.command != 'restart' }}
    working-directory: docker/${{ inputs.docker-folder }}
    run: |
      ecs-cli compose --project-name ${{ inputs.project-name }} service ${{ github.event.inputs.command }} --cluster-config ${{ inputs.config-name }} --ecs-profile ${{ inputs.profile-name }}

  - name: 'Compose service restart'
    if: ${{ github.event.inputs.command == 'restart' }}
    working-directory: docker/${{ inputs.docker-folder }}
    run: |
      ecs-cli compose --project-name ${{ inputs.project-name }} service stop --cluster-config ${{ inputs.config-name }} --ecs-profile ${{ inputs.profile-name }}
      ecs-cli compose --project-name ${{ inputs.project-name }} service start --cluster-config ${{ inputs.config-name }} --ecs-profile ${{ inputs.profile-name }}