name: 'Download SonarQube Static Code Analysis (SCA) Report'

on:
  workflow_call:
    secrets:
      sonarqube-host:
        required: true
      sonarqube-token:
        required: true
    inputs:
      sonar-project-key:
        description: 'Key of the project in SonarQube'
        required: true
        type: string

jobs:
  build:
    name: 'Download static code analysis report'
    timeout-minutes: 30

    runs-on: ubuntu-latest

    steps:
      - name: 'Getting repository name'
        run: echo "GITHUB_REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: 'Print action context'
        run: |
          echo "Repository: ${{ env.GITHUB_REPO_NAME }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: 'Setup JDK 1.11'
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: 'Download Sonar CNES Report tool'
        run: curl -L -O https://github.com/zenoolabs/github-actions/raw/main/bin/sonar-cnes-report.jar
      - name: 'Acquire Sonar Report'
        run: java -jar sonar-cnes-report.jar -s ${{ secrets.sonarqube-host }} -t ${{ secrets.sonarqube-token }} -p ${{ inputs.sonar-project-key }}
      - name: Get current date
        id: get-current-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: 'Upload Sonar report'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'sonar-analysis-report'
          path: ./${{ steps.get-current-date.outputs.date }}-${{ inputs.sonar-project-key }}-analysis-report.docx
