name: 'Build image'

on:
  workflow_call:
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true
      aws-access-key:
        required: true
      aws-secret-key:
        required: true
    inputs:
      region:
        required: true
        type: string
      image-repo:
        required: true
        type: string

jobs:
 buildImage:
  name: 'Build docker image'
  runs-on: ubuntu-latest
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-key }}
    AWS_REGION: ${{ inputs.region }}
    ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.nexus-username }}
    ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.nexus-password }}
  steps:
  - name: 'Setup ECS-CLI' #Amazon Elastic Container Service (ECS) command line interface -> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI.html
    uses: marocchino/setup-ecs-cli@v1
    with:
      version: v1.18.1

  - name: 'Checkout project'
    uses: actions/checkout@v2

  - name: 'Login to Amazon ECR' #Amazong Elastic Container Registry login action -> https://github.com/aws-actions/amazon-ecr-login
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1.5.0

  - name: 'Build and upload docker image' #JIB Gradle Plugin -> https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin
    run: ./gradlew jib --image ${{ inputs.image-repo }}