name: 'Pull Request Build for Legacy Stack'

on:
  workflow_call:
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true
    inputs:
      cache_version:
        description: 'A cache version passed from the caller workflow'
        required: false
        type: string
        default: 'v1'

jobs:
  build:
    name: 'Build and tests (legacy stack)'
    timeout-minutes: 30

    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.nexus-username }}
      ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.nexus-password }}

    services:
      mongodb:
        image: mongo:4.2.2
        ports:
          - 27017:27017

    steps:
      - name: 'Getting repository name'
        run: echo "GITHUB_REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: 'Print action context'
        run: |
          echo "Repository: ${{ env.GITHUB_REPO_NAME }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Cache gradle dependencies'
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ inputs.cache_version }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ inputs.cache_version }}-
      - name: 'Setup JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 'Grant execute permission for gradlew'
        run: chmod +x gradlew
      - name: 'Run build and tests'
        run: ./gradlew clean build --full-stacktrace
      - name: 'Upload test results'
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: test_results
          # Directory containing files to upload
          path: ./build/reports/tests/test
