name: 'SonarQube Static Code Analysis (SCA)'

on:
  workflow_call:
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true
      sonarqube-token:
        required: true
    inputs:
      sonar-project-key:
        description: 'Key of the project in SonarQube'
        required: true
        type: string
      sonarqube-host:
        type: string
        description: 'Sonarqube host url'
        required: true

jobs:
  build:
    name: 'Run static code analysis'
    timeout-minutes: 30

    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.nexus-username }}
      ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.nexus-password }}
      SONAR_TOKEN: ${{ secrets.sonarqube-token }}

    steps:
      - name: 'Getting repository name'
        run: echo "GITHUB_REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: 'Print action context'
        run: |
          echo "Repository: ${{ env.GITHUB_REPO_NAME }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Cache gradle dependencies'
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ inputs.cache-version }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ inputs.cache-version }}-
      - name: 'Setup JDK 11'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: 'Grant execute permission for gradlew'
        run: chmod +x gradlew
      - name: 'Run build and tests'
        run: ./gradlew clean check
      - name: 'Analyze dependencies'
        run: ./gradlew dependencyCheckAnalyze
      - name: 'Run SonarQube'
        run: ./gradlew sonarqube -Dsonar.projectKey=${{ inputs.sonar-project-key }} -Dsonar.host.url=${{ inputs.sonarqube-host }}
      - name: 'Upload dependency check report'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'dependency-check-report'
          path: ./build/reports/dependency-check-report.html
