name: 'SonarQube Static Code Analysis (SCA)'

on:
  workflow_call:
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true
      sonarqube-host:
        required: true
      sonarqube-token:
        required: true
    inputs:
      cache-version:
        description: 'A cache version passed from the caller workflow'
        required: false
        type: string
        default: 'v1'
      sonar-project-key:
        description: 'Key of the project in SonarQube'
        required: true
        type: string

jobs:
  build:
    name: 'Run static code analysis'
    timeout-minutes: 30

    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.nexus-username }}
      ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.nexus-password }}
      ORG_GRADLE_PROJECT_sonarqubeHostUrl: ${{ secrets.sonarqube-host }}
      ORG_GRADLE_PROJECT_sonarqubeLoginToken: ${{ secrets.sonarqube-token }}

    steps:
      - name: 'Getting repository name'
        run: echo "GITHUB_REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: 'Print action context'
        run: |
          echo "Repository: ${{ env.GITHUB_REPO_NAME }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Cache gradle dependencies'
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ inputs.cache-version }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ inputs.cache-version }}-
      - name: 'Setup JDK 1.11'
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: 'Grant execute permission for gradlew'
        run: chmod +x gradlew
      - name: 'Run build and tests'
        run: ./gradlew clean build
      - name: 'Analyze dependencies'
        run: ./gradlew dependencyCheckAnalyze
      - name: 'Run SonarQube'
        run: ./gradlew check sonarqube -Dsonar.projectKey=${{ inputs.sonar-project-key }} -Dsonar.projectName=${{ inputs.sonar-project-key }}
      - name: 'Download Sonar CNES Report tool'
        run: curl -O https://raw.githubusercontent.com/zenoolabs/github-actions/main/bin/sonar-cnes-report.jar
      - name: 'Acquire Sonar Report'
        run: java -jar sonar-cnes-report.jar -s ${{ secrets.sonarqube-host }} -t ${{ secrets.sonarqube-token }} -p ${{ inputs.sonar-project-key }}
      - name: Get current date
        id: get-current-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: 'Upload Sonar report'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'sonar-analysis-report'
          path: ./${{ steps.get-current-date.outputs.date }}-${{ inputs.sonar-project-key }}-analysis-report.docx
      - name: 'Upload dependency check report'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'dependency-check-report'
          path: ./build/reports/dependency-check-report.html
